### ISSUE TITLE
Clone method for optimizer

### ISSUE THREAD

**Issue by sebffischer** [mlverse/torch#1028]
It would be awesome if there was a clone method for the optimizer that creates deep clones of the optimizer's internal state. 
Currently, a shallow cone is created, see the example below:

``` r
library(data.table)
library(torch)

n = nn_linear(10, 1)
opt = optim_adagrad(n$parameters)

opt1 = opt$clone(deep = TRUE)

x1 = opt1$state_dict()$state$`1`$sum$clone()

x = torch_randn(16, 10)
y = mean(n(x))
y$backward()
opt$step()
#> NULL

x2 = opt1$state_dict()$state$`1`$sum

x3 = opt$state_dict()$state$`1`$sum

torch_equal(x1, x2)
#> [1] FALSE
torch_equal(x2, x3)
#> [1] TRUE
```

<sup>Created on 2023-05-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sebffischer** [comment]
So to be a little more clear:

I have an object that contains a network and an optimizer, where the optimizer was initialized on the parameters of the network. I want to create a deep clone of the object. For this, a deep clone of the network and the optimizer has to be created and the newly cloned optimizer should have the parameters of the cloned network as its parameters.

**Comment by dfalbel** [comment]
If we were to have a clone method it would need to take a `parameters` argument, because it probably doesn't make sense to clone the optimizer but keep refering to the same parameters. So I'm leaning towards not implementing a custom **deep** clone method for it.

With #1041, we made `load_state_dict()` clone the state dict as it moves it to the optimizer so you don't need to clone it manually. 

Let me know if this helps in your use case!

**Comment by sebffischer** [comment]
Thanks a lot for addressing this so quickly, it perfectly matches my use case :)
