### ISSUE TITLE
support cuda memory diagnostic functions

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#112]
```
cuda_memory_summary()
cuda_memory_allocated()
cuda_memory_reserved()
cuda_memory_empty_cache()
```

**Comment by jaredlander** [comment]
Was just going to ask about releasing memory. I have been experimenting with distance matrices for a GIS problem lately. I wrote a custom Rcpp function which is really fast, but on equally sized data, calling `torch::nnf_pdist()` blows it out of the water. Problem is, I have to compute the matrix about 1,000 times so I quickly run out of memory on the GPU. So having `cuda_memory_cache()` would be huge.

Obviously my use case is geared toward my needs, but I can see these memory functions being helpful for so many other people.

Since I am only asking for the feature and not actually providing any actual help, I hope that posting a link to the torch documentation is at least somewhat helpful: https://pytorch.org/docs/master/cuda.html#torch.cuda.empty_cache

**Comment by dfalbel** [comment]
Hi @jaredlander,

The R GC is not aware of the GPU memory and I think this is what causes the GPU memory to not be released.
One solution, if you are calling in a loop is to manually call `gc()` so you get the R object released and in turn the GPU memory back.

**Comment by jaredlander** [comment]
Oh fantastic, that's a great solution. It worked. I will note it doesn't appear to get released back to the OS as `nvidia-smi` still shows the memory be utilized until I restart R, but it allows me to make the next distance computation. Great stuff. Thanks for the help!

**Comment by dfalbel** [comment]
good to know. I'll investigate that, IUC the OS should get that memory back without any other manual call.
