### ISSUE TITLE
inconsistency in size() output 

### ISSUE THREAD

**Issue by skeydan** [mlverse/torch#259]
There is an inconsistency in `size()` output depending whether you're calling it on the result returned from indexing or a newly created tensor:

```
> t[1, 1]$size()
integer(0)

> torch_tensor(1)$size()
[1] 1
```

In Python, the latter case results in an empty list as well as the former:

```
>>> torch.tensor(1).size()
torch.Size([])
```

If you asked me, I'd actually prefer making this consistent by NOT doing what Python does - to me, returning a size of `1` in both cases seems intuitive...

**Comment by skeydan** [comment]
Hm... actually not so sure which way is the intuitive one here... when I compare

```
> m  <- matrix(1:4, nrow = 2)
> m[1,1] %>% dim()
NULL
> m[1,1, drop = FALSE] %>% dim()
[1] 1 1
```

this really does look more like Python does it...

**Comment by dfalbel** [comment]
The problem is that since R doesn't have a scalar type, we are converting a 1 element vector to a one element tensor (which makes sense) but currently there's no way to construct a scalar tensor (with no dimensions).

We could make `torch_tensor(1)` return a scalar tensor, but then there will be no way to construct a 1 element tensor directly from R. 

`t[1,1]` returns a scalar tensor and this might be confusing... I don't know what's the best solution here... I found sometimes functions expecting scalar tensors and had to `$squeeze` before passing, I also know that a lot of functions expect -element tensors.
