### ISSUE TITLE
Question on mapping from int64_t -> int

### ISSUE THREAD

**Issue by dirkschumacher** [mlverse/torch#329]
According to the [wiki](https://github.com/mlverse/torch/wiki/Design) `int64_t` is mapped to `int`.
As integers in R are just 32bits, wouldn't it make more sense to map it to `numerics` or `integer64`?

**Comment by dfalbel** [comment]
I haven't documented when deciding this, but my reasoning was:

1. It's better to convert integers from R to `torch_long()`ince most of torch functions expect floats, not integers.
2. Converting to integer64 by default is confusing for most R users, as `as_array(torch_tensor(1))` would return an integer64.
3. Converting to numerics is also problematic because comparisons don't work correctly.
4. It's quite rare to pass torch an R integer (not integer64)  and torch return a larger integer. I mean, most integers in torch are indexes and wouldn't be transformed in that way.

My decision in the end was that it was better to convert `torch_long()` to `integer()` (even if it doesn't work correctly for larger integers) and provide a `as.integer64` that converts `torch_long()` to `integer64` without any loss.

This leads to this problem. Ie, it silently fails for larger integers:

``` r
library(torch)
y <- bit64::as.integer64("12881829189281991")
x <- torch_tensor(y)
as_array(x)
#> [1] -1797101369
bit64::as.integer64(x)
#> integer64
#> [1] 12881829189281991
```

I am open to suggestions regarding the priority these 4 statements.
Thinking now, at least we should check for overflow when converting back to integers with `as_array`. Not sure though how much overhead this would cost.

**Comment by dirkschumacher** [comment]
We could check here if any value in `x` is larger or smaller than `.Machine$integer.max`:
https://github.com/mlverse/torch/blob/master/R/tensor.R#L303-L304

**Comment by dirkschumacher** [comment]
Also thanks a lot for the explanation and context!

**Comment by dfalbel** [comment]
Yeah! I think that would be great! I'd probably raise warning and return `NA` for those values like base R does:

``` r
as.integer("12881829189281982918")
#> Warning: NAs introduced by coercion to integer range
#> [1] NA
```

<sup>Created on 2020-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
