### ISSUE TITLE
Saving and loading models across devices

### ISSUE THREAD

**Issue by kailex** [mlverse/torch#395]
There might be different scenarios such as `save on a GPU / load on a CPU`, `save on a CPU / load on a GPU`. Thus, the `torch_load()` function has to have `map_location` argument in order to allow to load a model, e.g., on a device without CUDA:

    torch_load(PATH, map_location = device)

**Comment by dfalbel** [comment]
Thanks for reporting! Yes, currently, as a workaround you can move the model to the cpu before saving. Will make sure to implement this for the next release

**Comment by kailex** [comment]
Thank you for the quick response. Yes, it seems that a workaround 

    model$to(device = dev)
    torch_save(model, "model.pt")

works fine.

**Comment by mattwarkentin** [comment]
@dfalbel Do you think there is value in having `torch_save`/`torch_load` methods for `torch_Optimizer`, `dataset` and `dataloader` class objects? We can already save `torch_tensor` and `nn_module` objects. I think these other three classes are the last few important `torch` objects that would be nice to have `state_dict()` methods for so that they could be saved and loaded from disk. In the case of `optimizers` it would facilitate the ability to resume learning at a later point in time with the same optimizer state.

**Comment by dfalbel** [comment]
@mattwarkentin Yeah! That would be awesome! To save optimizers we might need to slightly refactor how we implement the state for each parameter. Currently they are saved in a slot in the `Tensor` environment and this might be tricky to recover.
