### ISSUE TITLE
Intel optimizations?

### ISSUE THREAD

**Issue by myoung3** [mlverse/torch#466]
From what I understand there are [three ](https://software.intel.com/content/www/us/en/develop/articles/getting-started-with-intel-optimization-of-pytorch.html) separate intel-related improvements to pytorch:
- oneDNN: optimizations built into (?) the current release of pytorch
- IPEX: intel "extensions" for pytorch
- oneCCL: for multi-node (?) distributed learning

Here's a good (recent) overview of these improvements:
https://medium.com/pytorch/accelerate-pytorch-with-ipex-and-onednn-using-intel-bf16-technology-dca5b8e6b58f

I'm guessing that using IPEX and oneCCL are not currently usable with torch in R, and I'm unsure whether oneDNN optimizations are incorporated (do they depend on python code? or just c++? Or are they only turned on via settings in IPEX?).  

Can you comment on whether you have plans on bringing in some of these optimizations?  I think there's probably a lot of researchers in the R community that would benefit from from these optimizations given universities tend to have large CPU-based HPC clusters.

It would also be nice to know whether getting intel optimizations working is a higher priority here or in tensorflow (https://github.com/rstudio/tensorflow/issues/453). My vote would be here, in torch, since the native solution is likely to work better.

**Comment by dfalbel** [comment]
Hi @myoung3 

AFAICT there are a few oneDNN (MKL DNN) optimizations that are implemented in core libtorch and we should get them for free. However I am not sure if this is enabled by default in pytorch.org LibTorch builds that we are using.

Regarding IPEX and oneCCL optimizations, we would need a reasonable amount of work to enable them in torch. We still have a few R side optimizations that should probably buy us much more relative performance gains, so we won't probably implement other devices eg IPEX and XLA at this time. 

In TensorFlow since we use whichever TensorFlow python version is installed on the system we should be able to get all the optimizations readily.

**Comment by myoung3** [comment]
Thanks for the response. It would be great if you could find out whether the onednn optimizations are turned on in the libtorch build now. I'm not sure how I would check that.  

It makes that the other optimizations would be lower priority relative to other improvements. Thanks for your work on the package!

**Comment by dfalbel** [comment]
I have added backend functions that allows us to query which optimizations LibTorch was compiled with:

``` r
torch::backends_mkl_is_available()
#> [1] TRUE
torch::backends_mkldnn_is_available()
#> [1] TRUE
torch::backends_openmp_is_available()
#> [1] FALSE
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So AFAICT, oneDNN is that is just a rebranding of MKLDNN and is available by default in LibTorch.
