### ISSUE TITLE
num_worker in dataloader opens many R sessions.

### ISSUE THREAD

**Issue by dcdorukcengiz** [mlverse/torch#622]
Hi all,

I am trying to use torch with multiple cpu's, so that I can get results quicker.
To the best of my understanding, the current recommended way to use multiple cpu's is increasing num_worker in dataloader. Also, in the now-closed issue #467, the recommended way to do it is to not use torch tensors in dataset object. 
Two unexpected things happen when I follow the recommended way:
1- It takes ages to train the model compared to the single core case (num_workers = 0)
2- Many many R Sessions are created in the background and they all eat up RAM. 

Here is an example:

``` r
suppressWarnings(library(torch))
suppressWarnings(library(tidyverse))
suppressWarnings(library(palmerpenguins))
train_data <- penguins %>% 
  select(bill_length_mm, bill_depth_mm,flipper_length_mm,body_mass_g) %>% 
  as.matrix()
x_train <- train_data[,2:4]
y_train <- train_data[ ,1 ,drop = FALSE]
#x_train <- torch_tensor(x_train, dtype = torch_float())
#y_train <- torch_tensor(y_train, dtype = torch_float())
torch_dataset <- dataset(
  name = "my_data",
  initialize = function() {
    self$x_train <- x_train
    self$y_train <- y_train
  },
  .getitem = function(index) {
    x <- self$x_train[index, ]
    y <- self$y_train[index, ]
    list(x, y)
  },
  .length = function() {
    nrow(x_train)
  }
)

train_ds <- torch_dataset()
train_dl <- train_ds %>%
  dataloader(batch_size = 25, num_workers = 4L)


net = nn_module(
  "class_net",
  initialize = function(){
    self$linear1 = nn_linear(3,1)
  },
  forward = function(x){
    x %>%
      self$linear1() %>% 
      torch_squeeze()
  }
)
model = net()
optimizer <- optim_adam(model$parameters)

train_batch <- function(b) {
  
  optimizer$zero_grad()
  output <- model(b[[1]])
  target <- b[[2]]
  
  loss <- nnf_mse_loss(output, target)
  loss$backward()
  optimizer$step()
  
}
for (epoch in 1:50) {
  model$train()
  coro::loop(for (b in train_dl) {
    loss <-train_batch(b)
  })
}
```

<sup>Created on 2021-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

![too_many_rsessions](https://user-images.githubusercontent.com/18427333/127222140-0fc76608-d93e-4b17-8828-ac28ace1e47f.png)

**Comment by dcdorukcengiz** [comment]
It seems that every time I run this simple code, something is written in my hard drive as well. For instance, the above code ate up about 1gb of my disk space and I am not sure what is saved.

**Comment by mattwarkentin** [comment]
Hi @dcdorukcengiz,

To your second point, `torch` does parallel data loading by using the `callr` package and spawing child `R` processed which can load the data in parallel and communicate back with the main `R` process. So this is the expected behaviour. When a dataloader is working, you should have a main `R` process and as many child `R` process as `num_workers`.

To the first point, there is a cost associated with spawning workers and then fetching the data from the child processes. So if producing a batch is a very quick operation (as is true in your example code), then the communication overhead between the main and child processes may actually take longer. You are most likely to see a benefit from parallel data loading when producing a single batch is slower than the communication cost of fetching data from parallel workers.

Hope this is helpful.

**Comment by dcdorukcengiz** [comment]
Hi @mattwarkentin 

Thank you for your answer.
Regarding your answer to my second point (your first point): I do not think this is expected behavior or I hope this is not the expected behavior. When I specify 4 workers, I'd expect to see 4 R sessions, not 50. Also, the RAM usage is really weird. This is a really small dataset, yet R seems to require more than 3.5GB of RAM. 
Also, what is written in the hard drive and where, is a mystery to me. I feel like each one of the R sessions are writing the data in hard drive somewhere, but not sure where (not in tempdir()).

**Comment by mattwarkentin** [comment]
Indeed, there shouldn't be 50 processes if you are only running a single main R session using a dataloader with 4 workers. However, how many times have you ran the code and possibly interrupted it with `cmd/ctrl + c` or pressing the stop sign in RStudio? The child processes may not be getting cleaned up properly if this happens and will be hanging in the background. Is this a possible explanation for the additional processes?

How do you know something is being written to disk? Could you please elaborate?

**Comment by dcdorukcengiz** [comment]
Hey,
Thanks for the follow-up.
With regards to your first point, I have run this once. I have opened a clean RStudio+Rsession and ran it. I did not interrupt it. No ctrl+c or pressing the stop sign.
All the 74 child processes are produced only from the code I attached above.
About something being written on disk: I have noticed a decline of about +1gb in my free space while reproducing this reprex. On this point, I cannot give you a definite answer as I have no idea what is saved or where. So, if torch has its own tempdir or working directory separate from the getwd(), that would be helpful.

**Comment by mattwarkentin** [comment]
Hmm. I'm not sure what the issue is then. Perhaps @dfalbel can shed more insight than I can.

**Comment by dfalbel** [comment]
I could reproduce this issue locally. 

What happens is that each epoch will open 4 session (this is expected, because each epoch will re-initialize the dataloader). 

However, it seems that R is not aware of the memory allocated by the sub processes thus it won't call the garbage collector, and it's the garbage collector that should trigger the function that shuts down the workers. Sometimes the garbage collector is called though, for different reasons probably and then the sessions are removed.

So in the for loop if you do something like:

```
for (epoch in 1:50) {
  model$train()
  coro::loop(for (b in train_dl) {
    loss <-train_batch(b)
  })
 gc() # calls the garbage collector
}
```

You will see that you no longer have that many open R sessions.
In practice, what I think I'll do to fix this issue is calling `gc` every time new workers are getting started, so we make sure that if the dataloader is called in aloop we won't have such problems.

I think adding a `gc` call before this chunk of code will fix this.

https://github.com/mlverse/torch/blob/d610292d3733c6f283d53efefb8e1459eb03e3fd/R/utils-data-dataloader.R#L328-L333

As for speed of parallel dataloaders, multiple variables have to be taken into account to see if it will be faster than loading data sequentially. See for example this slide: https://dfalbel.github.io/talks/2021-04-10-rladies-tunis/#30

The code to generate this plot can be found here: https://gist.github.com/dfalbel/c053c852bc95d671acf26e4cce9a789a

**Comment by dfalbel** [comment]
Regarding the disk space, parallel dataloaders are implemented using `callr` and `callr` should be writing inputs and outputs to subsessions by writing to tempfiles:

See eg: 

https://github.com/r-lib/callr/blob/7e6ac6414f32623dec533e7a69ff6f9c64d49885/R/setup.R#L12-L19

and https://github.com/r-lib/callr/blob/e6289d5722d1d70585e175fc7089a6c649733ce9/R/r-session.R#L434
