### ISSUE TITLE
Debugging backward() with register_hook(). And new solution?

### ISSUE THREAD

**Issue by dominikj2** [mlverse/torch#640]
Hi,

Whilst debugging issue #634, I've been using register_hook() for the autograd's backward pass. I'm getting this error message. 

```
Error in (function (tensors, dim)  : 
  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
 
The pytorch advice for this error message is to run `CUDA_LAUNCH_BLOCKING=1 python script.py` , but I don't know what an R equivalent is for passing `CUDA_LAUNCH_BLOCKING=1`?

In order to understand register_hook() I produced the below code, which gave me a thought (potential solution) for debugging autograd's backward pass. Why can't a tensor object have a functionality called Tensor$Browser (TRUE/FALSE) and when set as TRUE it executes a browser() during loss$backward() for all tensors with `grad_fn`.  

Tensor$browser would behave just like in the below functions (c_hook, d_hook and e_hook) but you can activate the browsers when calling loss$backward(Browser = TRUE) . I could be misunderstanding (missing crucial complexity) as it seems like there aren't any obvious solutions for debugging backwark() autograd.

```
a <- torch_tensor(2.0, requires_grad = TRUE)
b <- torch_tensor(3.0, requires_grad = TRUE)
c <- torch_tensor(2.0, requires_grad = TRUE)
c$register_hook(c_hook)

d = a*b
d$register_hook(d_hook)

e = d*c
e$register_hook(e_hook)

c_hook <- function(grad){
  browser()
  print(paste("c", as.character(as.array(grad))))
  return(grad)
}

d_hook <- function(grad){
  browser()
  print(paste("d", as.character(as.array(grad))))
  return(grad)
}

e_hook <- function(grad){
  browser()
  print(paste("e", as.character(as.array(grad))))
  return(grad)
}

# BACKWARDS
e$backward()
```

**Comment by dfalbel** [comment]
It looks like `CUDA_LAUNCH_BLOCKING=1` is a environment variable. You should be able to do `Sys.setenv(CUDA_LAUNCH_BLOCKING=1)` before loading torch for the first time in the session.

I like the idea of a `autograd_browser_hook()` method on tensors. However I don't think we will be able to have `loss$backward(browser=TRUE)`, it would be users responsibility to activate or not the hook for each tensor. Adding a backward global would add overhead and we don't easily control that code since it runs directly on LibTorch.
