### ISSUE TITLE
question on CRAN installations

### ISSUE THREAD

**Issue by jwijffels** [mlverse/torch#651]
I'm wondering how the CRAN setup looks like

- Did CRAN install LibTorch on their machines such that R CMD check works on their end without having to download the torch binaries and such that all your examples work in R CMD check?
I'm basically asking this to see how I need to structure the examples in https://github.com/bnosac/ETM to pass CRAN checks.

Regarding other R packages which depend on this R package
- Are there some expectations that you request regarding unit tests to make sure the packages still work when libtorch is upgraded?

**Comment by dfalbel** [comment]
Currently CRAN doesn't install LIbTorch so tests and examples that use torch can't run in their machines. 
In general I have been wrapping examples in

```
if (torch::torch_is_installed()) {
# example code
}
```

See eg: https://github.com/mlverse/tabnet/blob/main/R/explain.R#L17 or you can also use the `@examplesIf` roxygen2 directive.

For tests, you can also condition on `torch::torch_is_installed()`:

```
if (torch::torch_is_installed())
  test_check("tabnet")
```

Even though I have been using `TORCH_TEST` env var, for example: https://github.com/mlverse/tabnet/blob/main/tests/testthat.R#L4-L5 . Using the env var is slightly safer because it allows failure in your CI system if torch is not correctly installed while `torch::torch_is_installed()` could silently pass.

The same can be done for vignettes, you can add a chunk in the beginning that conditions evaluation on the presence of torch. For example (https://github.com/mlverse/tabnet/blob/main/vignettes/interpretation.Rmd#L13-L22)

```
knitr::opts_chunk$set(
  eval = torch::torch_is_installed()
)
```

LibTorch upgrades can cause breaking changes but in general those will be warned before (they are usually warned at LibTorch level) and we will do our best to help fixing those issues during revdep checks.

**Comment by jwijffels** [comment]
Thanks for the feedback on the use of `torch::torch_is_installed()` / `TORCH_TEST `
Would wrapping examples in a `\donttest` block be allowed on CRAN as well?

**Comment by dfalbel** [comment]
In my experience, they will complain when too many tests are wrapped in `\donttest` or `\dontrun` directives.

**Comment by jwijffels** [comment]
Thanks for all the docs and your time. It's clear what to do.
