### ISSUE TITLE
problems with convert R array to tensor as viseverse

### ISSUE THREAD

**Issue by mohamed-180** [mlverse/torch#653]

**Comment by mohamed-180** [comment]
from Examples :

`library(torch)`
`x <- array(runif(8), dim = c(2, 2, 2))`
`y <- torch_tensor(x, dtype = torch_float64())`
`y`
`#> torch_tensor`
`#> (1,.,.) = `
`#>   0.5955  0.3436`
`#>   0.4946  0.4344`
`#> `
`#> (2,.,.) = `
`#>   0.9322  0.7824`
`#>   0.6503  0.7516`
`#> [ CPUDoubleType{2,2,2} ]`
`identical(x, as_array(y))`
`#> [1] TRUE`

thats ok from array(x) to tensor(y)  

but 
`x <- torch_tensor(runif(8), dtype = torch_float64())`
`y <- as.array(x)`
`identical(x,y) `
gives 
#> [1] FASLE

**Comment by mohamed-180** [comment]
I think it returns to the difference between externalptr and R object (pointer vs object) .

is there is away to automatically make R treat tensor as array

**Comment by dfalbel** [comment]
I don't think there's a general way of doing that. A `torch_tensor` has other attributes that would have to be compared to make sure they are identical. Also it's not an array in the same sense as R - values might not be in a continuous chunk of memory, it can have other data types and etc.

You can create your own version of `identical` that knows how to compare them the way you want to define identity.

There's one tricky detail in your second example though:

``` r
library(torch)

x <- runif(8)
y <- torch_tensor(x, dtype = torch_float64())
z <- as.array(x)

all.equal(x, z)
#> [1] "Attributes: < target is NULL, current is list >"
#> [2] "target is numeric, current is array"
identical(x, z)
#> [1] FALSE


all.equal(x, as.numeric(z))
#> [1] TRUE
```

The value returned by `as.array()` is always an array, independently if it's an array with a single dimension.
`identical()` is then reporting that the objects are not 'identical' and that's because `runif()` returned an R vector, nor an array. You can use `as.numeric()` no make them identical.

**Comment by mohamed-180** [comment]
thanks ,
it was very clear
