### ISSUE TITLE
torch_ne(): output is not interpretable as logical

### ISSUE THREAD

**Issue by dominikj2** [mlverse/torch#657]
Hi.

Below example shows that `torch_equal()` can be used in an `if` statement, but this is not the case for `torch_ne(), torch_greater(), torch_greater_equal(), torch_less()` and `torch_less_equal()`. Reproducible example below: 

```
x <- torch_tensor(1L)
y <- torch_tensor(1L)

if(torch_equal(x, y)){
  print("in torch_equal")
}
# NO ERROR

x <- torch_tensor(1L)
y <- torch_tensor(2L)

if(torch_ne(x, y)){
  print("in torch_ne")
}

# Error in if (torch_ne(x, y)) { : argument is not interpretable as logical

torch_greater(x, y)
torch_greater_equal(x, y)
torch_less(x, y)
torch_less_equal(x, y)
# Error in if (torch_ne(x, y)) { : argument is not interpretable as logical
```
Note that Python `torch.ne` gives a `True/False` output that can be used in` if `statements. 
[https://pytorch.org/docs/stable/generated/torch.ne.html](url)
```
torch.ne(torch.tensor(1), torch.tensor(2))
tensor(True)
```
I imagine these logical statements would be most useful in `if `statements but Torch give error for this use.

**Comment by dfalbel** [comment]
`torch_ne(), torch_greater(), torch_greater_equal(), torch_less()` and `torch_less_equal()` all do element-wise comparisons, so they must return tensors, even if you are comparing scalar tensors. Even in python all of those functions return tensors.

`torch_equal` compares if 2 tensors have the same size and values. it's not doing element-wise comparisons. THus it returns a bool value. The equivalent element wise operation would be `torch_eq`.

Using boolean tensors in `if` statements in R is a limitation that we can't overcome. This is only possible in Python because `if` statements can use `__bool__` or `__len__` methods that return the builtin bool type. In R, you have to explicitly make the conversion. For example:

```
x <- torch_tensor(1L)
y <- torch_tensor(2L)

if(as.logical(torch_ne(x, y))){
  print("in torch_ne")
}
```

**Comment by dominikj2** [comment]
Thanks for clarifying

**Comment by mohamed-180** [comment]
I think here we must not treat `torch_tensor` which is "externalptr" as R object , so we have to use `as_array()` always to deal with it in R 
Ex:
```
x <- torch_tensor(1L)
y <- torch_tensor(2L)

if(torch_ne(x,y) %>% as_array()){
  print("in torch_ne")
}
```

**Comment by dominikj2** [comment]
Hi @mohamed-180, 

Thanks. 

Can you elaborate on why "we must not treat torch_tensor which is "externalptr" as R object"? Why is it better to use `as_array()`?

**Comment by dfalbel** [comment]
`as_array` should be equivalent to calling `as.logical()` the only difference is that `as.logical()`. would fail if you passed a numeric tensor for example, that can't be converted to booleans.

R tensors are external pointers and `if` statements in R always require boolean values.
