### ISSUE TITLE
print tensor information (enhancement)

### ISSUE THREAD

**Issue by mohamed-180** [mlverse/torch#661]
can print tensor : 
```
 x <- torch_tensor(c(1,2,3.0))
 x$requires_grad_()
```
look like :
> torch_tensor
 1
 2
 3
[ CPUFloatType{3} , requires_grad = TRUE]

and ` y -> x^3`

> torch_tensor
  1
  8
 27
[ CPUFloatType{3}  , grad_fn = PowBackward0]

**Comment by dfalbel** [comment]
That would be nice @mohamed-180 ! Do you want to contribute a PR?

**Comment by mohamed-180** [comment]
would you refer who to implement it (guide lines) ,
and i will work on it @dfalbel

**Comment by mohamed-180** [comment]
https://github.com/mlverse/torch/blob/3a160c03d864f8608b588058e34f41b52002866d/R/tensor.R#L42

can  it begins from above

**Comment by dfalbel** [comment]
Yes, you can modify that method. 

I think instead of `[ CPUFloatType{3} , requires_grad = TRUE]` you could print that in separate pair of brackets eg. `[ CPUFloatType{3} ][requires_grad = TRUE]`. This will make it easier because you would only need to do concatenate the string returned by the `cpp_` function.
