### ISSUE TITLE
Adding new `torch` extensions to `contrib`.

### ISSUE THREAD

**Issue by rdinnager** [mlverse/torch#735]
I've been slowly working my way through a port of a big Pytorch project to R `torch` (StyleGAN3: https://github.com/NVlabs/stylegan3). I've managed to make my way about half way through the Generator architecture, but now I need some Pytorch extensions used in the Stylegan3 repository. These include custom CUDA code (everything can be found here: https://github.com/NVlabs/stylegan3/tree/main/torch_utils/ops). By following this PR: https://github.com/mlverse/torch/pull/619, I was able to get one of the extensions working on a fork of the `torch` repo (the `bias_act` extension). But before I go ahead and expend energy on getting the other extensions to work, I just wanted to make sure it was okay to continue with this approach? This will require making a PR of these added extensions (which I am putting in the `contrib` section), and so I wanted to make sure you were okay with this contribution? There are two things to consider:

1) The extensions take quite awhile to compile, and so add an appreciable amount to the compilation time of `lantern`.
2) Is the license for these extensions acceptable for the `torch` project? The license can be found here: https://github.com/NVlabs/stylegan3/blob/main/LICENSE.txt . It is copyrighted by NVIDIA but it does grant the right to redistribution and modification, though use of the code is restricted to non-commercial purposes. A warning to users about this restriction could be included in the function documentation for functions using this contributed code. What do you think?

Alternatively, various hints around this repo suggest that there may soon be ways of adding extensions without having to add them to `torch` itself, but instead through a mechanism in a separate package. Am I correct that this functionality may be on the way, and if show, do you think I should wait for it? Obviously it would be nice (for me) to use the compilation infrastructure already setup for `torch`, but I'm interested in whatever options might be (or become) available.

Thanks very much for your time. (In case you are interested, early work on this project is here: https://github.com/rdinnager/styleganr).

**Comment by dfalbel** [comment]
Hey @rdinnager ! 

This is super nice work! Thanks for sharing!

I think for `contrib` we expect for much smaller scope functionality, like a simple activation function or like the sorting operator. Also, I am not sure about licensing, because we will actually compile that code into a single binary, I am afraid it's not as simple as not using the specific functionality. In theory I think we would need to have a way to opt-out that chunk of code at compilation time. 

You are right, we are working on a mechanism so users can extend torch with C++/CUDA code in separate packages and I think using it will be a better approach for styleganr!
Currently there's a WIP tutorial available [here](https://github.com/mlverse/lltm). It shouldn't be too much different to what you already did by following #619. We have a GH Actions workflow to help with the build infrastructure.

This functionality will be released soon and a few minor things might change, but I don't expect very large changes in what we already have in lltm. If you want to follow this way, I can offer help setting up that mechanism for you or we can schedule some time for synchronous help.

**Comment by rdinnager** [comment]
Cool! Thanks for pointing me to this, this is exactly what I was hoping was possible. I'm much happier to keep this all together in the package to be honest, and I totally understand how adding something big like this is not ideal for `contrib`. And indeed, it looks pretty similar to what I've already done, so it shouldn't be too hard to translate. I will have a go and let you know if I have any problems (thanks for the offer of help, I really appreciate it, and will definitely take you up on it if I have issues).

**Comment by rdinnager** [comment]
This approach seems to be working splendidly for me, so I'll close this issue. Thanks!
