### ISSUE TITLE
Doesn't work with CUDA 11.4

### ISSUE THREAD

**Issue by Philmod** [mlverse/torch#807]
Hi!

We upgraded our setup to CUDA 11.4 in order to use Tensorflow 2.6+, but then the Torch installation doesn't recognize CUDA anymore, even if I set the environment variable `Sys.setenv(CUDA="11.4")`.

Is there any workaround to make it work? Or is it mandatory to use CUDA 11.1 as specified in the [documentation](https://cran.r-project.org/web/packages/torch/vignettes/installation.html)

Thanks,
Mod

**Comment by dfalbel** [comment]
We officially support up until CUDA 10.2, 11.1 and 11.3 with the current CRAN version of torch (0.7.2). 

You can make torch think that you have CUDA 11.3 with eg. (`Sys.setenv(CUDA="11.3")` at installation time), and that should just work, unless there are ABI changes from CUDA 11.4- this is safe in general. Since we use pre-built binaries from LibTorch, we would need PyTorch's team to officially support CUDA 11.4 before we can add it on our end.

**Comment by Philmod** [comment]
Thanks @dfalbel, that tricks worked.

Do you know if the next version of Torch will support officially CUDA 11.4?

Feel free to close the bug.
