### ISSUE TITLE
Is there any way to troubleshoot why the installer doesn't find cuda ?

### ISSUE THREAD

**Issue by cyrilmory** [mlverse/torch#931]
According to the installation vignette (https://cran.r-project.org/web/packages/torch/vignettes/installation.html), one should install CUDA 11.3 and CUDNN 8.4 in default locations, and then just run `install.packages("torch")` in RStudio and "If you have followed default installation locations we will detect that you have CUDA software installed and automatically download the GPU enabled Lantern binaries". 
I have done that (or at least I think I have, but maybe I did something wrong) and yet the installer doesn't seem to detect cuda, and `torch::cuda_is_available()` returns false. And I'm thinking that I may not be the only one.
Is there a way to find out what's wrong ? Something like switching the installer to a verbose mode, in order to find out which CUDA-related file cannot be found, leading the installer to download only the CPU libraries ? If not, do you think it could be added easily ?

**Comment by dfalbel** [comment]
We use the following to find CUDA on Linux:

https://github.com/mlverse/torch/blob/71d1f143dc718c952dbce9a588631e3224d8463c/R/install.R#L281-L341

And on Windows:

https://github.com/mlverse/torch/blob/71d1f143dc718c952dbce9a588631e3224d8463c/R/install.R#L237-L266

You could try running line by line and see why it returns 'cpu' instead of 'cuda'.

I think it would be nice to have a verbose mode that prints on each step in the verification! Do you want to contribute a PR?

Also, depending on the CUDA version, NVIDIA might have changed the default location, thus our autodetect function might have broken. Let me know if you have additional information.

You can also force the installer to a specific CUDA version by specifying the `CUDA` envvar, for example `Sys.setenv("CUDA"= "11.3")`

**Comment by cyrilmory** [comment]
Thanks for your quick reply. I've been able to troubleshoot and fix the install for my computer, and I've just tried it and it works fine. I'm running windows and have installed NVidia CUDA 11.3 specifically for Torch. Just so you know : I didn't have env var "CUDA" set (apparently the NVIDIA installer hadn't created it) and my C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3 did not contain any "version.txt" file. There is a "version.json" file, though, but it does not contain a line "CUDA Version 11.3.0". I fixed the problem by adding a version.txt with that line in the folder, and setting the env var manually, and it worked.

Now for the PR : I'd gladly work on it this week. However I'm relatively new to R, so two quick questions :
- how would you turn the verbose mode on/off ? I'm thinking of checking for the TORCH_VERBOSE_INSTALL env var, and if it's "TRUE", activate the verbose mode, otherwise not. Any better suggestion ? 
- what is the best function to print the text to console ? I see you used "message" in install.R, should I stick with that or use print() or something else ?

**Comment by znmeb** [comment]
My experience with CUDA PyTorch is that you will have problems unless you follow the instructions here <https://pytorch.org/get-started/locally/> before attempting to use CUDA PyTorch. With R, make sure you install in the correct virtual environment. The default is a `conda` environment named `r-reticulate`.

The `r-reticulate` documentation isn't clear how this works; I ran into some issues on Windows.

**Comment by dfalbel** [comment]
@cyrilmory Cool that's great that you figured it out. 

`CUDA` en var is really intended to be set by the user, I think the installer set's `CUDA_PATH` and we actually look into the directory to get the version. Unfortunately the installer no longer adds the version.txt file and we need to figure out another way to get the version given the directory.

- I think an env var `TORCH_VERBOSE_INSTALL` is great, maybe just setting to 1 for enabled and 0 to disable, instead of `TRUE` to follow other env vars in the project.
- I think you can use `message()`, I think this is better because users can easily capture messages in a separate stream if necessary.

**Comment by cyrilmory** [comment]
I have written a small PR as a start. Turns out the installer created a version.json in my CUDA_PATH, so I switched to that instead of version.txt.
I will rework the PR until it meets the requirements in terms of style, etc, but I don't have much time today or in the coming days and wanted to at least start.
