### ISSUE TITLE
torch 0.9.0 and 0.9.1 deadlock when run in parallel

### ISSUE THREAD

**Issue by jonlachmann** [mlverse/torch#971]
Hi,

Pytorch/libtorch as of version 1.12 allows forking in combination with autograd when only using the CPU and not the GPU as in this issue here https://github.com/pytorch/pytorch/issues/69839.

Previously (up until 0.8.1), running torch from R inside mclapply through this package was possible when setting ```torch_set_num_threads(1)```. Now, a deadlock situation emerges when doing so.

I have created a minimal example (similar to as in a previous issue I created) the code is:

```
library(torch)
library(parallel)

testfun <- function (x) {
  lstm <- nn_lstm(50, 50)
  in_data <- torch_tensor(matrix(rnorm(50),1), torch_float())
  out_data <- torch_tensor(array(rnorm(2500), c(1,50,50)), torch_float())
  out_pred <- lstm(in_data)[[1]]
  loss <- nnf_mse_loss(out_pred, out_data)
  loss$backward()
}

mclapply(1:2, testfun)
```

When running this code, a number of threads are spawned, and a deadlock situation where the CPU usage is 0% and the code never completes is created.

The thread tree in htop looks like this:
![Screenshot 2023-01-27 at 11 33 27](https://user-images.githubusercontent.com/10993608/215068786-5508ad1e-a21a-49d9-b945-28497e56c0d2.png)

Investigating the threads in gdb we can see that there seems to be a lockup in the ```std::condition_variable``` used in lantern/utils.cpp. https://github.com/mlverse/torch/blob/8369336cc25df518f6791917ad2653661b1f1a28/lantern/src/utils.cpp#L325

We see two threads stuck here:
![cond_var1](https://user-images.githubusercontent.com/10993608/215069812-967ba99b-f0ec-4732-9957-20a3aa3784b6.png)
 
5 threads are stuck here: 
![cond_var3](https://user-images.githubusercontent.com/10993608/215069915-7973fdd5-af05-4742-b493-827d3d0319ef.png)

And 5 threads stuck in this location:
 ![cond_var9](https://user-images.githubusercontent.com/10993608/215070010-3795d5c4-b6db-46af-a97d-ab308d0bf29d.png)

There is also one thread in select.c:
![select](https://user-images.githubusercontent.com/10993608/215070111-608d039a-ea0f-4947-b02d-9aaea6855517.png)

One in nanosleep:
![sleep1](https://user-images.githubusercontent.com/10993608/215070194-b166b6d3-ed21-4f89-9af2-3ace593c8519.png)

Finally, there are two threads stopped in libgomp:
![thread](https://user-images.githubusercontent.com/10993608/215070306-d58e3728-df88-46f2-b821-a65d624d85b5.png)

I am unsure about which information may be relevant, and wanted to give a thorough example of the problem, hence the many screenshots. If more information is needed, let me know.

Examining the source between versions 0.8.1 and 0.9.0 I can see that a ```ThreadPool``` was added, and it has the possibly offending ```std::condition_variable```. My suspicion is that the same ```std::condition_variable``` is poked at from multiple threads created by ```mclapply```, which is not the intention as the ```ThreadPool``` will now be locked and unlocked in unintended ways, causing the deadlock.

I can continue debugging, but would love some input in how to proceed, and I think that someone more familiar with the code can probably give better pointers towards where to look. Also I should mention that I am overall very happy with the package, and think that it is really nice to be able to use libtorch so seamlessly from R.

**Comment by dfalbel** [comment]
Hi @jonlachmann,

Thanks for the detailed report. I still didn;t have time to look into it with more detail.
It sounds plausible that the EventLoop is responsible for the deadlock. 

The reason why we need that event loop is to be able to correctly garbage collect torch Tensors when running `backward()` from R. The R garbage collector can only run from the main thread but once it's running, it will call `lantern_delete_*` functions. We tried simply calling those function in another new thread, but that's not possible because PyTorch allocators hold a mutex that is necessary for freeing:

https://github.com/pytorch/pytorch/blob/fde220ca4450adce96abf198d4cbc114d6a32ef5/c10/cuda/CUDACachingAllocator.cpp#L814

https://github.com/pytorch/pytorch/blob/fde220ca4450adce96abf198d4cbc114d6a32ef5/c10/cuda/CUDACachingAllocator.cpp#L1039

This we need to schedule the `lantern_delete_*` calls to the same thread that is trying to allocate, which we do with that event loop:

 Here, lantern_delete is scheduling a call: 

https://github.com/mlverse/torch/blob/716dc41b1b51a3fdab359263951d1c11420ad6c4/src/lantern/src/Delete.cpp#L19-L22

That will be eventually executed with:

https://github.com/mlverse/torch/blob/8369336cc25df518f6791917ad2653661b1f1a28/lantern/src/Allocator.cpp#L76

Which basically waits for the condition variable:

https://github.com/mlverse/torch/blob/8369336cc25df518f6791917ad2653661b1f1a28/lantern/src/Allocator.cpp#L33-L37

The `delete_tasks` event loop is a global variable defined here: https://github.com/mlverse/torch/blob/8369336cc25df518f6791917ad2653661b1f1a28/lantern/src/Allocator.cpp#L23 and I think this might be causing the problem with forking that you are seeing. Maybe global variables like this are not copied when forking? We could try initializing them with a NULL value and allocate it when loading lantern for the first time, if that's the cause.

I have no experience at all with forking, and I'm not sure I completely understand what happens with that code when the OS forks the process. I will try to dig some more intothis next week.

**Comment by dfalbel** [comment]
Hi @jonlachmann,

I think #979 should fix this issue. The problem is that the thread pool was initialized as a global variable and forking when there are active threads is not safe (as per eg https://stackoverflow.com/a/59133193). We now only initialize the thread pool upon the first call to backward, so it should be safe to use fork based parallelism before any call to `backward()`.

We could further add a compilation option to initialize and clear the thread pool on every backward call. This would remove that constraint on the R side. I'm not sure if LibTorch would allow this though, because I think they also start a thread pool for backward calls.

Let me know if this works for you. I basically took the reproducible example that you posted and added as a unit test so we don't regress on this.

**Comment by jonlachmann** [comment]
Hi!

I can verify that it works in my specific real use case as well! Thanks for this! =) If it is possible to get a new CRAN release soon with this integrated that would be even better! =)
