### ISSUE TITLE
Install/support libtorch 1.13+

### ISSUE THREAD

**Issue by ctrapnell** [mlverse/torch#974]
Hi! Amazing work. 

I am running into trouble with using torch on Apple silicon (GPU), largely because some key features aren't supported on the MPS device in libtorch 1.12.1. According to the PyTorch folks, 1.13 substantially improves support on the Apple GPU. Would it be possible to pull 1.13.1 (or later) in install_torch()?  

Thank you!

**Comment by dfalbel** [comment]
HI @ctrapnell ,

We still do not support LibTorch 1.13 but will move to it in the near future. Specially for m1 macs there's some extra amount of work because we need to port a patch that allows us to correctly the R garbage collector within the Metal Allocator: https://github.com/mlverse/libtorch-mac-m1/blob/main/patch/MPSAllocator-v1.12.1.patch

I think it might still take us a few weeks to get into this, sorry.

**Comment by dfalbel** [comment]
Just merged #977 which adds support for 1.13.1.
